### ISSUE TITLE
Option to extract HTML

### ISSUE THREAD

**Issue by xcapt** [tspannhw/nifi-extracttext-processor#3]
Hi,
Great job on this processor!
As tika allows HTML extraction of multiple document formats, do you think it is feasible to have an option to output HTML in this processor ?

**Comment by tspannhw** [comment]
That sounds like a good idea, let me work on that

**Comment by tspannhw** [comment]
Okay completed

**Comment by xcapt** [comment]
just... wow ;)
thanks

**Comment by tspannhw** [comment]
https://community.hortonworks.com/content/kbentry/177370/extracting-html-from-pdf-excel-and-word-documents.html
